### ISSUE TITLE
Netbeans Maven Repositories

### ISSUE THREAD

**Issue by njss** [EyeTribe/tet-java-client#11]
It seems that the only reason why I am not able to use bintray (eyetribe) is because you are not publishing an index at bintray (if I got it right...).
It is really annoying not to be able to connect to jcenter or bintray jfrog with Netbeans.
Any help you can provide me?

Thank you.

**Comment by arnebp** [comment]
The Eye Tribe community has been using this repository through jcenter for a long while now.  This is the first problem of the nature reported. Are you sure this is not a problem with your local setup? 

Have you set up Jcenter in NetBeans as instructed from their wiki? http://wiki.netbeans.org/FaqAddingNewUpdateCenter

**Comment by arnebp** [comment]
@njss have you had any success with this one?
