### ISSUE TITLE
virtualbox

### ISSUE THREAD

**Issue by KannarFr** [EyeTribe/tet-java-client#18]
Hi, 

I'm using an VirtualBox machine running Windows 10 to use Eyetribe Server/UI on Ubuntu 16.04 host. All USB devices are readable except the EyeTribe. Any add-on or protection to fix/disable ? Should I open ticket on VirtualBox support ?

Regards,

Kannar.

**Comment by arnebp** [comment]
Issues regarding hardware should be posted in the EyeTribe dev forum http://theeyetribe.com/forum/.

I have not come across anyone who has successfully set up VirtualBox to run with the EyeTribe Tracker. The USB3 support of that product has been reported to be inadequate.  Issues regarding that product should be reported to people behind it.

I've heard of people using VMware having more success.
