### ISSUE TITLE
onGazeUpdate not working with new SDK

### ISSUE THREAD

**Issue by honzzyk** [EyeTribe/tet-java-client#5]
Hello,

I am trying to use the new SDK (v.0.9.60) and the code from your websites gives mi no output - I can not get the gaze data from the eye tribe. 

```
package com.theeyetribe.javafx;

import com.theeyetribe.clientsdk.GazeManager;
import com.theeyetribe.clientsdk.IGazeListener;
import com.theeyetribe.clientsdk.data.GazeData;

public class TETSimple {
	public static void main(String[] args) {
		final GazeManager gm = GazeManager.getInstance();
		boolean success = gm.activate();
		final GazeListener gazeListener = new GazeListener();
		gm.addGazeListener(gazeListener);
		Runtime.getRuntime().addShutdownHook(new Thread() {
			@Override
			public void run() {
				gm.removeGazeListener(gazeListener);
				gm.deactivate();
			}
		});
	}

	private static class GazeListener implements IGazeListener {
		@Override
		public void onGazeUpdate(GazeData gazeData) {
			System.out.println(gazeData.toString());
		}
	}
}
```

**Comment by arnebp** [comment]
I would advice you to take a look at the sample that is part of the SDK. See module 'javafx-sample'. Also, you may find answers in our developer forum http://theeyetribe.com/forum/

**Comment by honzzyk** [comment]
I have tried the javafx-calibration code from the sdk with the same problem. The method "onGazeUpdate" is never called, so the calibration is not working (images of eyes are not showed etc.). Start of the app is OK, no errors. The only problem is that the onGazeUpdate method is never called. With the older sdk I use EyeTribe without problems.

**Comment by arnebp** [comment]
If you are not able to run the 'javafx-sample' then something is wrong in your setup. Does your development environment fulfill all requirements explained in the [main page](https://github.com/EyeTribe/tet-java-client)? Are you able to run the [pre-built release](https://github.com/EyeTribe/tet-java-client/releases)?

**Comment by honzzyk** [comment]
I can run the "EyeTribeJavaFx.jar" without problem. But if I try to run my own code, the new API is not working for me. 

I did this: I created a new project in eclipse, add "eyetribe-java-0.9.60.jar" to the build path, created a new class with the mentioned code and run it. But the "onGazeUpdate" method is never called. Is the code OK? It is copied from [here](http://dev.theeyetribe.com/java/) - I just deleted "ApiVersion.VERSION_1_0, ClientMode.PUSH" because it seem it is not compatible with new API.

**Comment by arnebp** [comment]
The situation you are experiencing has nothing to do with the SDK. It related to your program design. Your program exits immediately because the main method contains no mechanism to keep the program running. Reading [this](http://stackoverflow.com/questions/29930239/what-is-the-best-way-to-keep-a-java-program-running-forever-very-long-time) may help you.

Questions regarding Java program design are better suited for our [developer forum](http://theeyetribe.com/forum/viewforum.php?f=24&sid=839202241bfa28fdc289238043ff60df). Please post questions of that nature there so others can benefit from the answers.

Since your problem does not originate in the SDK I will go ahead and close this issue.

**Comment by honzzyk** [comment]
You are wrong, the code works with the older SDK. 

Even if I use this code as you suggest, the SKD doesnt work and the onGazeUpdate is never called. I have tried it in Eclipse and IntelliJ... There must be some problem in the SDK.


```
import com.theeyetribe.clientsdk.GazeManager;
import com.theeyetribe.clientsdk.IGazeListener;
import com.theeyetribe.clientsdk.data.GazeData;

public class TETSimple {
	public static void main(String[] args) throws InterruptedException {
		final GazeManager gm = GazeManager.getInstance();
		boolean success = gm.activate();

		final GazeListener gazeListener = new GazeListener();
		gm.addGazeListener(gazeListener);

		while (true) {
			System.out.println("asdfsdfa");
			Thread.sleep(1000);
		}
	}

	private static class GazeListener implements IGazeListener {
		@Override
		public void onGazeUpdate(GazeData gazeData) {
			System.out.println(gazeData.toString());
		}
	}
}
```

**Comment by arnebp** [comment]
I have written the following test program to verify your claim.

```
public class Main
{
    public static void main(String[] args) throws InterruptedException {
        final GazeManager gm = GazeManager.getInstance();
        boolean success = gm.activate();

        final GazeListener gazeListener = new GazeListener();
        gm.addGazeListener(gazeListener);

        long stamp = System.currentTimeMillis();
        long period = 5 * 1000;

        while(true)
        {
            System.out.println("time left... " + (period - (System.currentTimeMillis() - stamp)) + " ms");
            if((System.currentTimeMillis() - stamp) > period)
                break;
            Thread.sleep(100);
        }

        Runtime.getRuntime().addShutdownHook(new Thread()
        {
            @Override
            public void run()
            {
                gm.removeGazeListener(gazeListener);
                gm.deactivate();
                System.out.println("Closing program");
            }
        });

        System.exit(0);
    }

    private static class GazeListener implements IGazeListener
    {
        @Override
        public void onGazeUpdate(GazeData gazeData)
        {
            System.out.println(gazeData.toString());
        }
    }
}
```

This works perfectly when using a locally built version of the SDK library. 

I then followed your instructions and downloaded the prebuilt SDK library JAR from the release section. Using this, I was able to recreate the error you are experiencing. The JAR that had been uploaded was the wrong version. This has now been corrected. Thank you for your persistence!.

**Comment by honzzyk** [comment]
Ok, great. Thanks for the new version. It works great. :+1:
