### ISSUE TITLE
Mistake in the javafx-sample code

### ISSUE THREAD

**Issue by honzzyk** [EyeTribe/tet-java-client#6]
Hello,

I am trying to use the sample calibration in "javafx-sample" and I found a bug. The ImageView "gazeIndicator" is not placed in the preview well. The gaze point does not correspondent with the center of the circle-image. I think the method "getGazeIndicatorAnchor" in SceneController should be written in a different way.

**Comment by arnebp** [comment]
Right you are. Fixed in latest merge.
